# Generated by Django 4.2.28 on 2026-02-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional image URL for service card'),
        ),
        migrations.AddField(
            model_name='staff',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional photo URL'),
        ),
    ]
