# Generated by Django 4.2.28 on 2026-02-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_image_url_staff_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='location',
            field=models.CharField(blank=True, help_text='Branch or area e.g. Chembur, Bandra', max_length=100),
        ),
    ]
